version: '3.1'


services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d my_database -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
  myapp:
    container_name: userapi
    image: userapi
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure
